#Print
print('Hola mundo')
print(123)
print(True)
#Variables 
number = 1
string = 'Letters'
boolean = True
#Funcion type()
print(type(number))
print(type(string))
print(type(boolean))
#Operadores aritmeticos
#Suma(+)
print(1 + 1)
#Resta(-)
print(10 - 8)
#Multiplicacion(*) 
print(2 * 1)
#Division(/)
print(4 / 2)
#Resto
print(20 % 6)
#Operadores de asignacion 
#Asignacion basica
x = 1
print(x)
#Agregar valor a una variable
x += 1
print(x)
#Quitar valor a una variable 
x -= 1 
print(x)
#Dividir el valor de una variable
x /= 1 
print(x)
#Multiplicar el valor de una variable 
x *= 2
print(x)
